version: '3'

services:

  go-api:
    build: ./go-api
    ports:
      - "8080:8080"
    environment:
      NODE_API_URL: http://node-api:3000

  node-api:
    build: ./node-api
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - go-api